eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8087/eureka/
spring:
  application:
    name: gateway
server:
  port: 8084
zuul:
  routes:
    service: /service0/**
    service2: /service2/**