server:
  port: 8006
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/jijiayue/SpringCloud    # 配置git仓库的地址
          search-paths: config-repo                                          # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: jijiayue                                                  # git仓库的账号
          password: 15275263276yun                                            # git仓库的密码


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8087/eureka/